owner: ptrdms
repo: status

sites:
  - name: MAIN WEB
    url: $MAINWEB
    icon: https://raw.githubusercontent.com/ptrdms/upptime/master/assets/web.png
    maxResponseTime : 3000
    expectedStatusCodes:
      - 200
      - 201
      - 403
      - 404

status-website:
  cname: $DOMAINS
  favicon: https://raw.githubusercontent.com/ptrdms/upptime/master/assets/uptime.png
  logoUrl: https://raw.githubusercontent.com/ptrdms/upptime/master/assets/uptime.png
  name: Uptime Monitor
  theme: night
  navbar:
    - title: Home
      href: /
    - title: Feed
      href: $DOMAINS

commitMessages:
  commitAuthorName: "ptrdms-bot"
  commitAuthorEmail: "$BOTPTRDMS"

i18n:
  footer: This page displays the uptime status of our services
  
robotsText: "User-agent: * \n Disallow: /"
